apiVersion: apps/v1
kind: Deployment

metadata:
  name: desafio-api
  namespace: desafio-api

spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 20%
  replicas: 5
  selector:
    matchLabels:
      api: desafio-api
  template:
    metadata:
      labels:
        api: desafio-api
    spec:
      containers:
        - name: desafio-api
          image: thiago0503/challenge-api:v4
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: desafio-api-config
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 2
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
            initialDelaySeconds: 5
          resources:
            requests:
              cpu: 400m
              memory: 256Mi
            limits:
              cpu: 700m
              memory: 512Mi
