apiVersion: apps/v1
kind: Deployment

metadata:
  name: desafio-db
  namespace: desafio-db
spec:
  replicas: 1
  selector:
    matchLabels:
      api: desafio-db
  template:
    metadata:
      labels:
        api: desafio-db
    spec:
      containers:
        - name: challenge-db
          image: bitnami/postgresql
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: db-credentials
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 700m
              memory: 512Mi
          volumeMounts:
            - name: postgres-persistent-data
              mountPath: /app/lib/postgresql/data
      volumes:
        - name: postgres-persistent-data
          persistentVolumeClaim:
            claimName: postgres-pvc
