apiVersion: v1
kind: Service

metadata:
  name: desafio-api-service
  namespace: desafio-api
spec:
  selector:
    api: desafio-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000 # Porta do cluster acessível internamente
      targetPort: 3000 # Porta usada pelo container
      nodePort: 30007 # Porta exposta externamente
