apiVersion: v1
kind: Service

metadata:
  name: desafio-db-svc
  namespace: desafio-db

spec:
  type: ClusterIP
  selector:
    api: desafio-db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
