apiVersion: v1
kind: Service

metadata:
  name: desafio-api-svc
  namespace: desafio-api

spec:
  type: ClusterIP
  selector:
    api: desafio-api
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
